export const THINKING_LABELS: string[] = [
  'pondering',
  'brewing',
  'musing',
  'ruminating',
  'weaving',
  'scheming',
  'concocting',
  'plotting',
  'forging',
  'cogitating',
  'divining',
  'incanting',
  'tinkering',
  'conjuring',
  'distilling',
  'simmering',
  'sketching',
  'composing',
  'architecting',
  'whittling',
  'chiseling',
  'spelunking',
  'untangling',
  'unraveling',
  'threading',
  'polishing',
  'harmonizing',
  'orchestrating',
  'scribing',
  'kindling',
  'crystallizing',
  'decanting',
  'percolating',
  'stoking the forge',
  'chasing a thought',
  'wrangling electrons',
  'aligning bits',
  'debugging reality',
  'chasing the muse',
  'consulting the oracle',
  'reading the tea leaves',
  'tuning the strings',
  'lighting the kiln',
  'shaping clay',
  'finding words',
  'sharpening the blade',
  'summoning muses',
  'breathing in',
  'wandering a while',
  'piecing it together',
  'stirring the pot',
  'tracing threads',
  'knitting logic',
  'carving paths',
  'folding ideas',
  'quenching steel',
  'polishing gears',
  'bending light',
  'taming dragons',
  'counting stars',
  'hunting bugs',
  'tending embers',
  'listening closely',
  'tracing roots',
  'drawing the map',
  'stacking stones',
  'untying the knot',
  'peeking under the hood',
  'rolling the dice',
  'painting pixels',
  'reading between the lines',
  'spinning yarn',
  'pressing on',
  'warming up',
  'getting warmer',
  'splicing wires',
  'measuring twice',
  'shaping the void',
  'tilling the soil',
  'sowing seeds',
  'grinding lenses',
  'pruning branches',
  'gathering wool',
  'turning the crank',
  'raising the sail',
  'charting a course',
  'casting runes',
  'oiling the cogs',
  'fanning the flames',
  'threading the needle',
  'mapping the maze',
  'walking the tree',
  'counting sheep',
  'steeping tea',
  'kneading dough',
  'whisking sparks',
  'minting ideas',
  'sanding edges',
  'weaving syntax',
  'stitching logic',
  'bartering with ghosts',
  'listening to the wind',
  'asking the rubber duck',
  'rearranging atoms',
  'coaxing photons',
  'reciting incantations',
  'feeding the hamster',
  'oiling the gears',
  'waking the daemons',
  'negotiating with types',
  'herding lambdas',
  'corralling callbacks',
  'untangling promises',
  'watering algorithms',
  'feeding the compiler',
  'befriending the linter',
  'chatting with the parser',
];

export function pickThinkingLabel(): string {
  const i = Math.floor(Math.random() * THINKING_LABELS.length);
  return THINKING_LABELS[i]!;
}
